[package]
name = "chipioindustries/mock-data-store-service"
description = "A DataStoreService clone for simulating network and data conditions in tests."
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"